SELECT NUM, COUNT(*)
FROM (
SELECT A, COUNT(DISTINCT B, D) AS NUM
FROM R4
GROUP BY A
) X
GROUP BY NUM;


SELECT NUM AS A_dependent_on_B_if_this_column_is_1, COUNT(*) AS TOTAL_COUNT
FROM (
SELECT A, COUNT(DISTINCT B) AS NUM
FROM R1
GROUP BY A
) AS SQ1
GROUP BY NUM
HAVING NUM = 1;

SELECT COUNT(*) AS MVD 
FROM (SELECT A
      FROM R2
      GROUP BY A
      HAVING (COUNT(DISTINCT B) * COUNT(DISTINCT C) 
                   <> COUNT(*))
) X;

SELECT COUNT(*) AS MVD 
FROM (SELECT A
      FROM R1
      GROUP BY A
      HAVING (COUNT(DISTINCT B) * COUNT(DISTINCT C) 
                   <> COUNT(*))
) X;


SELECT COUNT(*),
FROM(
SELECT NUM, COUNT(*) AS TOTAL_COUNT
FROM (
SELECT A, COUNT(DISTINCT B) AS NUM
FROM R4
GROUP BY A
) AS SQ1
GROUP BY NUM
) AS SQ2

--WORKY!!!
SELECT CASE
    WHEN COUNT(*) = 0 THEN 'MAYBE MVD'
    ELSE 'NO MVD'
    END
    AS MVD 
FROM (SELECT A
      FROM R2
      GROUP BY A
      HAVING (COUNT(DISTINCT B) * COUNT(DISTINCT C) 
                   <> COUNT(*))
) X;
----------------!!!YKROW

SELECT CASE
    WHEN COUNT(*) = 0 THEN 'MAYBE MVD'
    ELSE 'NO MVD'
    END
    AS MVD 
FROM (SELECT A
      FROM R2
      GROUP BY A
      HAVING (COUNT(DISTINCT B) * COUNT(DISTINCT C) 
                   <> COUNT(*))
) X;