SELECT CASE
	WHEN COUNT(*) = 0 THEN 'Rentals: PID-->HID,MAYBE MVD'
	ELSE 'Rentals: PID-->HID,NO MVD'
	END
	AS MVD
FROM (SELECT PID
	FROM Rentals
	GROUP BY PID
	HAVING (COUNT(DISTINCT HID) 
		<> COUNT(*))
) X;

SELECT CASE
	WHEN COUNT(*) = 0 THEN 'Coffees: DID-->HID,CID,MAYBE MVD'
	ELSE 'Coffees: DID-->HID,CID,NO MVD'
	END
	AS MVD
FROM (SELECT DID
	FROM Coffees
	GROUP BY DID
	HAVING (COUNT(DISTINCT HID) * COUNT(DISTINCT CID) 
		<> COUNT(*))
) X;

SELECT CASE
	WHEN COUNT(*) = 0 THEN 'Projects: ID-->PID,SID,MAYBE MVD'
	ELSE 'Projects: ID-->PID,SID,NO MVD'
	END
	AS MVD
FROM (SELECT ID
	FROM Projects
	GROUP BY ID
	HAVING (COUNT(DISTINCT PID) * COUNT(DISTINCT SID) 
		<> COUNT(*))
) X;

