--Rentals

INSERT INTO Rentals_HZ_HC SELECT DISTINCT HZ, HC FROM Rentals;
INSERT INTO Rentals_HID_HS_HZ SELECT DISTINCT HID, HS, HZ FROM Rentals;
INSERT INTO Rentals_PID_PN SELECT DISTINCT PID, PN FROM Rentals;
INSERT INTO Rentals_PID_HID_S SELECT DISTINCT PID, HID, S FROM Rentals;

--Coffees

INSERT INTO Coffees_DID_DN_DS SELECT DISTINCT DID, DN, DS FROM Coffees;
INSERT INTO Coffees_CID_CN_CM SELECT DISTINCT CID, CN, CM FROM Coffees;
INSERT INTO Coffees_DID_HID_CID SELECT DISTINCT DID, HID, CID FROM Coffees;

--Projects

INSERT INTO Projects_SID_SN SELECT DISTINCT SID, SN FROM Projects;
INSERT INTO Projects_PID_PN SELECT DISTINCT PID, PN FROM Projects;
INSERT INTO Projects_ID_MID_MN SELECT DISTINCT ID, MID, MN FROM Projects;
INSERT INTO Projects_ID_PID_SID SELECT DISTINCT ID, PID, SID FROM Projects;

--Customers

INSERT INTO Customers_CZ_CC SELECT DISTINCT CZ, CC FROM Customers;
INSERT INTO Customers_CID_CN_CS_CNr_CZ_EID SELECT DISTINCT CID, CN, CS, CNr, CZ, EID FROM Customers;